# Generated by Django 5.1.4 on 2025-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descrption', models.TextField(blank=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
