# Generated by Django 5.1.4 on 2025-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0002_dummymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/dummy/'),
        ),
    ]
