# Generated by Django 5.2 on 2025-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodel',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
