# Generated by Django 5.1.4 on 2025-05-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_customusermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'verbose_name': 'CustomUserModel'},
        ),
    ]
