# Generated by Django 5.1.4 on 2025-05-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_alter_customusermodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_staff',
        ),
    ]
