# Generated by Django 5.2 on 2025-04-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('generic', '0002_alter_genericmodel_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoriesModel',
            fields=[
                ('genericmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generic.genericmodel')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.categories')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
            bases=('generic.genericmodel',),
        ),
    ]
