# Generated by Django 5.2 on 2025-04-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoriesmodel',
            old_name='description',
            new_name='subCategorydescription',
        ),
        migrations.RenameField(
            model_name='subcategoriesmodel',
            old_name='name',
            new_name='subCategoryname',
        ),
    ]
