# Generated by Django 5.1.4 on 2025-05-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('generic', '0002_alter_genericmodel_extra_data'),
        ('subcategories', '0002_rename_description_subcategoriesmodel_subcategorydescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('genericmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generic.genericmodel')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stocks', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='media/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.categories')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='subcategories.subcategoriesmodel')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
            bases=('generic.genericmodel',),
        ),
    ]
