# Generated by Django 5.1.4 on 2025-05-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
